# backend/Dockerfile.dev
FROM golang:1.22-alpine

WORKDIR /app

# Устанавливаем Air
RUN go install github.com/air-verse/air@v1.52.3

# Копируем go.mod и go.sum и качаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код
COPY . .

# Запускаем Air для hot-reload
CMD ["air", "-c", ".air.toml"]
